//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Paytools.Rti.Model._2023 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1", IsNullable=false)]
    public partial class FullPaymentSubmission {
        
        private FullPaymentSubmissionEmpRefs empRefsField;
        
        private string relatedTaxYearField;
        
        private object[] itemsField;
        
        private FullPaymentSubmissionFinalSubmission finalSubmissionField;
        
        /// <remarks/>
        public FullPaymentSubmissionEmpRefs EmpRefs {
            get {
                return this.empRefsField;
            }
            set {
                this.empRefsField = value;
            }
        }
        
        /// <remarks/>
        public string RelatedTaxYear {
            get {
                return this.relatedTaxYearField;
            }
            set {
                this.relatedTaxYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompressedPart", typeof(FullPaymentSubmissionCompressedPart))]
        [System.Xml.Serialization.XmlElementAttribute("Employee", typeof(FullPaymentSubmissionEmployee))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionFinalSubmission FinalSubmission {
            get {
                return this.finalSubmissionField;
            }
            set {
                this.finalSubmissionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmpRefs {
        
        private string officeNoField;
        
        private string payeRefField;
        
        private string aORefField;
        
        private string sAUTRField;
        
        private string cOTAXRefField;
        
        /// <remarks/>
        public string OfficeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
            }
        }
        
        /// <remarks/>
        public string PayeRef {
            get {
                return this.payeRefField;
            }
            set {
                this.payeRefField = value;
            }
        }
        
        /// <remarks/>
        public string AORef {
            get {
                return this.aORefField;
            }
            set {
                this.aORefField = value;
            }
        }
        
        /// <remarks/>
        public string SAUTR {
            get {
                return this.sAUTRField;
            }
            set {
                this.sAUTRField = value;
            }
        }
        
        /// <remarks/>
        public string COTAXRef {
            get {
                return this.cOTAXRefField;
            }
            set {
                this.cOTAXRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionCompressedPart {
        
        private FullPaymentSubmissionCompressedPartType typeField;
        
        private byte[] valueField;
        
        public FullPaymentSubmissionCompressedPart() {
            this.typeField = FullPaymentSubmissionCompressedPartType.gzip;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(FullPaymentSubmissionCompressedPartType.gzip)]
        public FullPaymentSubmissionCompressedPartType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionCompressedPartType {
        
        /// <remarks/>
        zip,
        
        /// <remarks/>
        gzip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployee {
        
        private FullPaymentSubmissionEmployeeEmployeeDetails employeeDetailsField;
        
        private FullPaymentSubmissionEmployeeEmployment[] employmentField;
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetails EmployeeDetails {
            get {
                return this.employeeDetailsField;
            }
            set {
                this.employeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employment")]
        public FullPaymentSubmissionEmployeeEmployment[] Employment {
            get {
                return this.employmentField;
            }
            set {
                this.employmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployeeDetails {
        
        private string nINOField;
        
        private FullPaymentSubmissionEmployeeEmployeeDetailsName nameField;
        
        private FullPaymentSubmissionEmployeeEmployeeDetailsAddress addressField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmployeeDetailsGender genderField;
        
        private string passportNumberField;
        
        private FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetails partnerDetailsField;
        
        /// <remarks/>
        public string NINO {
            get {
                return this.nINOField;
            }
            set {
                this.nINOField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetailsName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetailsAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetailsGender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string PassportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetails PartnerDetails {
            get {
                return this.partnerDetailsField;
            }
            set {
                this.partnerDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployeeDetailsName {
        
        private string ttlField;
        
        private string[] foreField;
        
        private string initialsField;
        
        private string surField;
        
        /// <remarks/>
        public string Ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fore")]
        public string[] Fore {
            get {
                return this.foreField;
            }
            set {
                this.foreField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Sur {
            get {
                return this.surField;
            }
            set {
                this.surField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployeeDetailsAddress {
        
        private string[] lineField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public string[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForeignCountry", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UKPostcode", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        ForeignCountry,
        
        /// <remarks/>
        UKPostcode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmployeeDetailsGender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetails {
        
        private string nINOField;
        
        private FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetailsName nameField;
        
        /// <remarks/>
        public string NINO {
            get {
                return this.nINOField;
            }
            set {
                this.nINOField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetailsName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployeeDetailsPartnerDetailsName {
        
        private string[] foreField;
        
        private string initialsField;
        
        private string surField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fore")]
        public string[] Fore {
            get {
                return this.foreField;
            }
            set {
                this.foreField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Sur {
            get {
                return this.surField;
            }
            set {
                this.surField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmployment {
        
        private FullPaymentSubmission_YesType offPayrollWorkerField;
        
        private bool offPayrollWorkerFieldSpecified;
        
        private FullPaymentSubmission_YesType occPenIndField;
        
        private bool occPenIndFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentDirectorsNIC directorsNICField;
        
        private bool directorsNICFieldSpecified;
        
        private string taxWkOfApptOfDirectorField;
        
        private FullPaymentSubmissionEmployeeEmploymentStarter starterField;
        
        private string payIdField;
        
        private FullPaymentSubmissionEmployeeEmploymentPayIdChgd payIdChgdField;
        
        private FullPaymentSubmission_YesType paymentToANonIndividualField;
        
        private bool paymentToANonIndividualFieldSpecified;
        
        private FullPaymentSubmission_YesType irrEmpField;
        
        private bool irrEmpFieldSpecified;
        
        private System.DateTime leavingDateField;
        
        private bool leavingDateFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentFiguresToDate figuresToDateField;
        
        private FullPaymentSubmissionEmployeeEmploymentPayment paymentField;
        
        private FullPaymentSubmissionEmployeeEmploymentNIlettersAndValues[] nIlettersAndValuesField;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType OffPayrollWorker {
            get {
                return this.offPayrollWorkerField;
            }
            set {
                this.offPayrollWorkerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OffPayrollWorkerSpecified {
            get {
                return this.offPayrollWorkerFieldSpecified;
            }
            set {
                this.offPayrollWorkerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType OccPenInd {
            get {
                return this.occPenIndField;
            }
            set {
                this.occPenIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OccPenIndSpecified {
            get {
                return this.occPenIndFieldSpecified;
            }
            set {
                this.occPenIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentDirectorsNIC DirectorsNIC {
            get {
                return this.directorsNICField;
            }
            set {
                this.directorsNICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectorsNICSpecified {
            get {
                return this.directorsNICFieldSpecified;
            }
            set {
                this.directorsNICFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TaxWkOfApptOfDirector {
            get {
                return this.taxWkOfApptOfDirectorField;
            }
            set {
                this.taxWkOfApptOfDirectorField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentStarter Starter {
            get {
                return this.starterField;
            }
            set {
                this.starterField = value;
            }
        }
        
        /// <remarks/>
        public string PayId {
            get {
                return this.payIdField;
            }
            set {
                this.payIdField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPayIdChgd PayIdChgd {
            get {
                return this.payIdChgdField;
            }
            set {
                this.payIdChgdField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType PaymentToANonIndividual {
            get {
                return this.paymentToANonIndividualField;
            }
            set {
                this.paymentToANonIndividualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentToANonIndividualSpecified {
            get {
                return this.paymentToANonIndividualFieldSpecified;
            }
            set {
                this.paymentToANonIndividualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType IrrEmp {
            get {
                return this.irrEmpField;
            }
            set {
                this.irrEmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IrrEmpSpecified {
            get {
                return this.irrEmpFieldSpecified;
            }
            set {
                this.irrEmpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime LeavingDate {
            get {
                return this.leavingDateField;
            }
            set {
                this.leavingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LeavingDateSpecified {
            get {
                return this.leavingDateFieldSpecified;
            }
            set {
                this.leavingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentFiguresToDate FiguresToDate {
            get {
                return this.figuresToDateField;
            }
            set {
                this.figuresToDateField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPayment Payment {
            get {
                return this.paymentField;
            }
            set {
                this.paymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NIlettersAndValues")]
        public FullPaymentSubmissionEmployeeEmploymentNIlettersAndValues[] NIlettersAndValues {
            get {
                return this.nIlettersAndValuesField;
            }
            set {
                this.nIlettersAndValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmission_YesType {
        
        /// <remarks/>
        yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentDirectorsNIC {
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        AL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentStarter {
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentStarterStartDec startDecField;
        
        private bool startDecFieldSpecified;
        
        private FullPaymentSubmission_YesType studentLoanField;
        
        private bool studentLoanFieldSpecified;
        
        private FullPaymentSubmission_YesType postgradLoanField;
        
        private bool postgradLoanFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentStarterSeconded secondedField;
        
        private FullPaymentSubmissionEmployeeEmploymentStarterOccPension occPensionField;
        
        private FullPaymentSubmissionEmployeeEmploymentStarterStatePension statePensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentStarterStartDec StartDec {
            get {
                return this.startDecField;
            }
            set {
                this.startDecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDecSpecified {
            get {
                return this.startDecFieldSpecified;
            }
            set {
                this.startDecFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType StudentLoan {
            get {
                return this.studentLoanField;
            }
            set {
                this.studentLoanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StudentLoanSpecified {
            get {
                return this.studentLoanFieldSpecified;
            }
            set {
                this.studentLoanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType PostgradLoan {
            get {
                return this.postgradLoanField;
            }
            set {
                this.postgradLoanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostgradLoanSpecified {
            get {
                return this.postgradLoanFieldSpecified;
            }
            set {
                this.postgradLoanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentStarterSeconded Seconded {
            get {
                return this.secondedField;
            }
            set {
                this.secondedField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentStarterOccPension OccPension {
            get {
                return this.occPensionField;
            }
            set {
                this.occPensionField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentStarterStatePension StatePension {
            get {
                return this.statePensionField;
            }
            set {
                this.statePensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentStarterStartDec {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentStarterSeconded {
        
        private FullPaymentSubmission_YesType itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private FullPaymentSubmission_YesType eEACitizenField;
        
        private bool eEACitizenFieldSpecified;
        
        private FullPaymentSubmission_YesType ePM6Field;
        
        private bool ePM6FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InOutUK", typeof(FullPaymentSubmission_YesType))]
        [System.Xml.Serialization.XmlElementAttribute("Stay183DaysOrMore", typeof(FullPaymentSubmission_YesType))]
        [System.Xml.Serialization.XmlElementAttribute("StayLessThan183Days", typeof(FullPaymentSubmission_YesType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public FullPaymentSubmission_YesType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType EEACitizen {
            get {
                return this.eEACitizenField;
            }
            set {
                this.eEACitizenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EEACitizenSpecified {
            get {
                return this.eEACitizenFieldSpecified;
            }
            set {
                this.eEACitizenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType EPM6 {
            get {
                return this.ePM6Field;
            }
            set {
                this.ePM6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EPM6Specified {
            get {
                return this.ePM6FieldSpecified;
            }
            set {
                this.ePM6FieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        InOutUK,
        
        /// <remarks/>
        Stay183DaysOrMore,
        
        /// <remarks/>
        StayLessThan183Days,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentStarterOccPension {
        
        private FullPaymentSubmission_YesType bereavedField;
        
        private bool bereavedFieldSpecified;
        
        private decimal amountField;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType Bereaved {
            get {
                return this.bereavedField;
            }
            set {
                this.bereavedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BereavedSpecified {
            get {
                return this.bereavedFieldSpecified;
            }
            set {
                this.bereavedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentStarterStatePension {
        
        private FullPaymentSubmission_YesType bereavedField;
        
        private bool bereavedFieldSpecified;
        
        private decimal amountField;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType Bereaved {
            get {
                return this.bereavedField;
            }
            set {
                this.bereavedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BereavedSpecified {
            get {
                return this.bereavedFieldSpecified;
            }
            set {
                this.bereavedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPayIdChgd {
        
        private FullPaymentSubmission_YesType payrollIdChangedIndicatorField;
        
        private string oldPayrollIdField;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType PayrollIdChangedIndicator {
            get {
                return this.payrollIdChangedIndicatorField;
            }
            set {
                this.payrollIdChangedIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string OldPayrollId {
            get {
                return this.oldPayrollIdField;
            }
            set {
                this.oldPayrollIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentFiguresToDate {
        
        private decimal taxablePayField;
        
        private decimal totalTaxField;
        
        private decimal studentLoansTDField;
        
        private bool studentLoansTDFieldSpecified;
        
        private decimal postgradLoansTDField;
        
        private bool postgradLoansTDFieldSpecified;
        
        private decimal benefitsTaxedViaPayrollYTDField;
        
        private bool benefitsTaxedViaPayrollYTDFieldSpecified;
        
        private decimal empeePenContribnsPaidYTDField;
        
        private bool empeePenContribnsPaidYTDFieldSpecified;
        
        private decimal empeePenContribnsNotPaidYTDField;
        
        private bool empeePenContribnsNotPaidYTDFieldSpecified;
        
        /// <remarks/>
        public decimal TaxablePay {
            get {
                return this.taxablePayField;
            }
            set {
                this.taxablePayField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalTax {
            get {
                return this.totalTaxField;
            }
            set {
                this.totalTaxField = value;
            }
        }
        
        /// <remarks/>
        public decimal StudentLoansTD {
            get {
                return this.studentLoansTDField;
            }
            set {
                this.studentLoansTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StudentLoansTDSpecified {
            get {
                return this.studentLoansTDFieldSpecified;
            }
            set {
                this.studentLoansTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PostgradLoansTD {
            get {
                return this.postgradLoansTDField;
            }
            set {
                this.postgradLoansTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostgradLoansTDSpecified {
            get {
                return this.postgradLoansTDFieldSpecified;
            }
            set {
                this.postgradLoansTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BenefitsTaxedViaPayrollYTD {
            get {
                return this.benefitsTaxedViaPayrollYTDField;
            }
            set {
                this.benefitsTaxedViaPayrollYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BenefitsTaxedViaPayrollYTDSpecified {
            get {
                return this.benefitsTaxedViaPayrollYTDFieldSpecified;
            }
            set {
                this.benefitsTaxedViaPayrollYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeePenContribnsPaidYTD {
            get {
                return this.empeePenContribnsPaidYTDField;
            }
            set {
                this.empeePenContribnsPaidYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpeePenContribnsPaidYTDSpecified {
            get {
                return this.empeePenContribnsPaidYTDFieldSpecified;
            }
            set {
                this.empeePenContribnsPaidYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeePenContribnsNotPaidYTD {
            get {
                return this.empeePenContribnsNotPaidYTDField;
            }
            set {
                this.empeePenContribnsNotPaidYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpeePenContribnsNotPaidYTDSpecified {
            get {
                return this.empeePenContribnsNotPaidYTDFieldSpecified;
            }
            set {
                this.empeePenContribnsNotPaidYTDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPayment {
        
        private string bacsHashCodeField;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentPayFreq payFreqField;
        
        private System.DateTime pmtDateField;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentLateReason lateReasonField;
        
        private bool lateReasonFieldSpecified;
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        private string periodsCoveredField;
        
        private FullPaymentSubmission_YesType aggregatedEarningsField;
        
        private bool aggregatedEarningsFieldSpecified;
        
        private FullPaymentSubmission_YesType pmtAfterLeavingField;
        
        private bool pmtAfterLeavingFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentHoursWorked hoursWorkedField;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentTaxCode taxCodeField;
        
        private decimal taxablePayField;
        
        private decimal nonTaxOrNICPmtField;
        
        private bool nonTaxOrNICPmtFieldSpecified;
        
        private decimal dednsFromNetPayField;
        
        private bool dednsFromNetPayFieldSpecified;
        
        private decimal payAfterStatDednsField;
        
        private bool payAfterStatDednsFieldSpecified;
        
        private decimal benefitsTaxedViaPayrollField;
        
        private bool benefitsTaxedViaPayrollFieldSpecified;
        
        private decimal class1ANICsYTDField;
        
        private bool class1ANICsYTDFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentCar[] benefitsField;
        
        private decimal empeePenContribnsPaidField;
        
        private bool empeePenContribnsPaidFieldSpecified;
        
        private decimal itemsSubjectToClass1NICField;
        
        private bool itemsSubjectToClass1NICFieldSpecified;
        
        private decimal empeePenContribnsNotPaidField;
        
        private bool empeePenContribnsNotPaidFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecovered studentLoanRecoveredField;
        
        private decimal postgradLoanRecoveredField;
        
        private bool postgradLoanRecoveredFieldSpecified;
        
        private decimal taxDeductedOrRefundedField;
        
        private FullPaymentSubmission_YesType onStrikeField;
        
        private bool onStrikeFieldSpecified;
        
        private FullPaymentSubmission_YesType unpaidAbsenceField;
        
        private bool unpaidAbsenceFieldSpecified;
        
        private decimal sMPYTDField;
        
        private bool sMPYTDFieldSpecified;
        
        private decimal sPPYTDField;
        
        private bool sPPYTDFieldSpecified;
        
        private decimal sAPYTDField;
        
        private bool sAPYTDFieldSpecified;
        
        private decimal shPPYTDField;
        
        private bool shPPYTDFieldSpecified;
        
        private decimal sPBPYTDField;
        
        private bool sPBPYTDFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPayment[] trivialCommutationPaymentField;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentFlexibleDrawdown flexibleDrawdownField;
        
        /// <remarks/>
        public string BacsHashCode {
            get {
                return this.bacsHashCodeField;
            }
            set {
                this.bacsHashCodeField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentPayFreq PayFreq {
            get {
                return this.payFreqField;
            }
            set {
                this.payFreqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PmtDate {
            get {
                return this.pmtDateField;
            }
            set {
                this.pmtDateField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentLateReason LateReason {
            get {
                return this.lateReasonField;
            }
            set {
                this.lateReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LateReasonSpecified {
            get {
                return this.lateReasonFieldSpecified;
            }
            set {
                this.lateReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MonthNo", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("WeekNo", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PeriodsCovered {
            get {
                return this.periodsCoveredField;
            }
            set {
                this.periodsCoveredField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType AggregatedEarnings {
            get {
                return this.aggregatedEarningsField;
            }
            set {
                this.aggregatedEarningsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AggregatedEarningsSpecified {
            get {
                return this.aggregatedEarningsFieldSpecified;
            }
            set {
                this.aggregatedEarningsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType PmtAfterLeaving {
            get {
                return this.pmtAfterLeavingField;
            }
            set {
                this.pmtAfterLeavingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PmtAfterLeavingSpecified {
            get {
                return this.pmtAfterLeavingFieldSpecified;
            }
            set {
                this.pmtAfterLeavingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentHoursWorked HoursWorked {
            get {
                return this.hoursWorkedField;
            }
            set {
                this.hoursWorkedField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentTaxCode TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxablePay {
            get {
                return this.taxablePayField;
            }
            set {
                this.taxablePayField = value;
            }
        }
        
        /// <remarks/>
        public decimal NonTaxOrNICPmt {
            get {
                return this.nonTaxOrNICPmtField;
            }
            set {
                this.nonTaxOrNICPmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NonTaxOrNICPmtSpecified {
            get {
                return this.nonTaxOrNICPmtFieldSpecified;
            }
            set {
                this.nonTaxOrNICPmtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal DednsFromNetPay {
            get {
                return this.dednsFromNetPayField;
            }
            set {
                this.dednsFromNetPayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DednsFromNetPaySpecified {
            get {
                return this.dednsFromNetPayFieldSpecified;
            }
            set {
                this.dednsFromNetPayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PayAfterStatDedns {
            get {
                return this.payAfterStatDednsField;
            }
            set {
                this.payAfterStatDednsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PayAfterStatDednsSpecified {
            get {
                return this.payAfterStatDednsFieldSpecified;
            }
            set {
                this.payAfterStatDednsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal BenefitsTaxedViaPayroll {
            get {
                return this.benefitsTaxedViaPayrollField;
            }
            set {
                this.benefitsTaxedViaPayrollField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BenefitsTaxedViaPayrollSpecified {
            get {
                return this.benefitsTaxedViaPayrollFieldSpecified;
            }
            set {
                this.benefitsTaxedViaPayrollFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Class1ANICsYTD {
            get {
                return this.class1ANICsYTDField;
            }
            set {
                this.class1ANICsYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Class1ANICsYTDSpecified {
            get {
                return this.class1ANICsYTDFieldSpecified;
            }
            set {
                this.class1ANICsYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Car", IsNullable=false)]
        public FullPaymentSubmissionEmployeeEmploymentPaymentCar[] Benefits {
            get {
                return this.benefitsField;
            }
            set {
                this.benefitsField = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeePenContribnsPaid {
            get {
                return this.empeePenContribnsPaidField;
            }
            set {
                this.empeePenContribnsPaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpeePenContribnsPaidSpecified {
            get {
                return this.empeePenContribnsPaidFieldSpecified;
            }
            set {
                this.empeePenContribnsPaidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ItemsSubjectToClass1NIC {
            get {
                return this.itemsSubjectToClass1NICField;
            }
            set {
                this.itemsSubjectToClass1NICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemsSubjectToClass1NICSpecified {
            get {
                return this.itemsSubjectToClass1NICFieldSpecified;
            }
            set {
                this.itemsSubjectToClass1NICFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeePenContribnsNotPaid {
            get {
                return this.empeePenContribnsNotPaidField;
            }
            set {
                this.empeePenContribnsNotPaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EmpeePenContribnsNotPaidSpecified {
            get {
                return this.empeePenContribnsNotPaidFieldSpecified;
            }
            set {
                this.empeePenContribnsNotPaidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecovered StudentLoanRecovered {
            get {
                return this.studentLoanRecoveredField;
            }
            set {
                this.studentLoanRecoveredField = value;
            }
        }
        
        /// <remarks/>
        public decimal PostgradLoanRecovered {
            get {
                return this.postgradLoanRecoveredField;
            }
            set {
                this.postgradLoanRecoveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PostgradLoanRecoveredSpecified {
            get {
                return this.postgradLoanRecoveredFieldSpecified;
            }
            set {
                this.postgradLoanRecoveredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxDeductedOrRefunded {
            get {
                return this.taxDeductedOrRefundedField;
            }
            set {
                this.taxDeductedOrRefundedField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType OnStrike {
            get {
                return this.onStrikeField;
            }
            set {
                this.onStrikeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnStrikeSpecified {
            get {
                return this.onStrikeFieldSpecified;
            }
            set {
                this.onStrikeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType UnpaidAbsence {
            get {
                return this.unpaidAbsenceField;
            }
            set {
                this.unpaidAbsenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UnpaidAbsenceSpecified {
            get {
                return this.unpaidAbsenceFieldSpecified;
            }
            set {
                this.unpaidAbsenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SMPYTD {
            get {
                return this.sMPYTDField;
            }
            set {
                this.sMPYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SMPYTDSpecified {
            get {
                return this.sMPYTDFieldSpecified;
            }
            set {
                this.sMPYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SPPYTD {
            get {
                return this.sPPYTDField;
            }
            set {
                this.sPPYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPPYTDSpecified {
            get {
                return this.sPPYTDFieldSpecified;
            }
            set {
                this.sPPYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SAPYTD {
            get {
                return this.sAPYTDField;
            }
            set {
                this.sAPYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SAPYTDSpecified {
            get {
                return this.sAPYTDFieldSpecified;
            }
            set {
                this.sAPYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ShPPYTD {
            get {
                return this.shPPYTDField;
            }
            set {
                this.shPPYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShPPYTDSpecified {
            get {
                return this.shPPYTDFieldSpecified;
            }
            set {
                this.shPPYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SPBPYTD {
            get {
                return this.sPBPYTDField;
            }
            set {
                this.sPBPYTDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SPBPYTDSpecified {
            get {
                return this.sPBPYTDFieldSpecified;
            }
            set {
                this.sPBPYTDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TrivialCommutationPayment")]
        public FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPayment[] TrivialCommutationPayment {
            get {
                return this.trivialCommutationPaymentField;
            }
            set {
                this.trivialCommutationPaymentField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentFlexibleDrawdown FlexibleDrawdown {
            get {
                return this.flexibleDrawdownField;
            }
            set {
                this.flexibleDrawdownField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentPayFreq {
        
        /// <remarks/>
        W1,
        
        /// <remarks/>
        W2,
        
        /// <remarks/>
        W4,
        
        /// <remarks/>
        M1,
        
        /// <remarks/>
        M3,
        
        /// <remarks/>
        M6,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        IR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentLateReason {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        MonthNo,
        
        /// <remarks/>
        WeekNo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentHoursWorked {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        E,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentTaxCode {
        
        private FullPaymentSubmission_YesType basisNonCumulativeField;
        
        private bool basisNonCumulativeFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentTaxCodeTaxRegime taxRegimeField;
        
        private bool taxRegimeFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FullPaymentSubmission_YesType BasisNonCumulative {
            get {
                return this.basisNonCumulativeField;
            }
            set {
                this.basisNonCumulativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BasisNonCumulativeSpecified {
            get {
                return this.basisNonCumulativeFieldSpecified;
            }
            set {
                this.basisNonCumulativeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FullPaymentSubmissionEmployeeEmploymentPaymentTaxCodeTaxRegime TaxRegime {
            get {
                return this.taxRegimeField;
            }
            set {
                this.taxRegimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxRegimeSpecified {
            get {
                return this.taxRegimeFieldSpecified;
            }
            set {
                this.taxRegimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentTaxCodeTaxRegime {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentCar {
        
        private string makeField;
        
        private System.DateTime firstRegdField;
        
        private string cO2Field;
        
        private string zeroEmissionsMileageField;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentCarFuel fuelField;
        
        private string idField;
        
        private FullPaymentSubmission_YesNoType amendmentField;
        
        private decimal priceField;
        
        private System.DateTime availFromField;
        
        private decimal cashEquivField;
        
        private System.DateTime availToField;
        
        private bool availToFieldSpecified;
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentCarFreeFuel freeFuelField;
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FirstRegd {
            get {
                return this.firstRegdField;
            }
            set {
                this.firstRegdField = value;
            }
        }
        
        /// <remarks/>
        public string CO2 {
            get {
                return this.cO2Field;
            }
            set {
                this.cO2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string ZeroEmissionsMileage {
            get {
                return this.zeroEmissionsMileageField;
            }
            set {
                this.zeroEmissionsMileageField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentCarFuel Fuel {
            get {
                return this.fuelField;
            }
            set {
                this.fuelField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesNoType Amendment {
            get {
                return this.amendmentField;
            }
            set {
                this.amendmentField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AvailFrom {
            get {
                return this.availFromField;
            }
            set {
                this.availFromField = value;
            }
        }
        
        /// <remarks/>
        public decimal CashEquiv {
            get {
                return this.cashEquivField;
            }
            set {
                this.cashEquivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime AvailTo {
            get {
                return this.availToField;
            }
            set {
                this.availToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailToSpecified {
            get {
                return this.availToFieldSpecified;
            }
            set {
                this.availToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentPaymentCarFreeFuel FreeFuel {
            get {
                return this.freeFuelField;
            }
            set {
                this.freeFuelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentCarFuel {
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        A,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmission_YesNoType {
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentCarFreeFuel {
        
        private System.DateTime providedField;
        
        private decimal cashEquivField;
        
        private System.DateTime withdrawnField;
        
        private bool withdrawnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Provided {
            get {
                return this.providedField;
            }
            set {
                this.providedField = value;
            }
        }
        
        /// <remarks/>
        public decimal CashEquiv {
            get {
                return this.cashEquivField;
            }
            set {
                this.cashEquivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Withdrawn {
            get {
                return this.withdrawnField;
            }
            set {
                this.withdrawnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WithdrawnSpecified {
            get {
                return this.withdrawnFieldSpecified;
            }
            set {
                this.withdrawnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecovered {
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecoveredPlanType planTypeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecoveredPlanType PlanType {
            get {
                return this.planTypeField;
            }
            set {
                this.planTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentStudentLoanRecoveredPlanType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPayment {
        
        private FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPaymentType typeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPaymentType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentPaymentTrivialCommutationPaymentType {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentPaymentFlexibleDrawdown {
        
        private FullPaymentSubmission_YesType flexiblyAccessingPensionRightsField;
        
        private bool flexiblyAccessingPensionRightsFieldSpecified;
        
        private FullPaymentSubmission_YesType pensionDeathBenefitField;
        
        private bool pensionDeathBenefitFieldSpecified;
        
        private FullPaymentSubmission_YesType seriousIllHealthLumpSumField;
        
        private bool seriousIllHealthLumpSumFieldSpecified;
        
        private decimal taxablePaymentField;
        
        private bool taxablePaymentFieldSpecified;
        
        private decimal nontaxablePaymentField;
        
        private bool nontaxablePaymentFieldSpecified;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType FlexiblyAccessingPensionRights {
            get {
                return this.flexiblyAccessingPensionRightsField;
            }
            set {
                this.flexiblyAccessingPensionRightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlexiblyAccessingPensionRightsSpecified {
            get {
                return this.flexiblyAccessingPensionRightsFieldSpecified;
            }
            set {
                this.flexiblyAccessingPensionRightsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType PensionDeathBenefit {
            get {
                return this.pensionDeathBenefitField;
            }
            set {
                this.pensionDeathBenefitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PensionDeathBenefitSpecified {
            get {
                return this.pensionDeathBenefitFieldSpecified;
            }
            set {
                this.pensionDeathBenefitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType SeriousIllHealthLumpSum {
            get {
                return this.seriousIllHealthLumpSumField;
            }
            set {
                this.seriousIllHealthLumpSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeriousIllHealthLumpSumSpecified {
            get {
                return this.seriousIllHealthLumpSumFieldSpecified;
            }
            set {
                this.seriousIllHealthLumpSumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxablePayment {
            get {
                return this.taxablePaymentField;
            }
            set {
                this.taxablePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxablePaymentSpecified {
            get {
                return this.taxablePaymentFieldSpecified;
            }
            set {
                this.taxablePaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal NontaxablePayment {
            get {
                return this.nontaxablePaymentField;
            }
            set {
                this.nontaxablePaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NontaxablePaymentSpecified {
            get {
                return this.nontaxablePaymentFieldSpecified;
            }
            set {
                this.nontaxablePaymentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionEmployeeEmploymentNIlettersAndValues {
        
        private FullPaymentSubmissionEmployeeEmploymentNIlettersAndValuesNIletter nIletterField;
        
        private decimal grossEarningsForNICsInPdField;
        
        private decimal grossEarningsForNICsYTDField;
        
        private decimal atLELYTDField;
        
        private decimal lELtoPTYTDField;
        
        private decimal pTtoUELYTDField;
        
        private decimal totalEmpNICInPdField;
        
        private decimal totalEmpNICYTDField;
        
        private decimal empeeContribnsInPdField;
        
        private decimal empeeContribnsYTDField;
        
        /// <remarks/>
        public FullPaymentSubmissionEmployeeEmploymentNIlettersAndValuesNIletter NIletter {
            get {
                return this.nIletterField;
            }
            set {
                this.nIletterField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrossEarningsForNICsInPd {
            get {
                return this.grossEarningsForNICsInPdField;
            }
            set {
                this.grossEarningsForNICsInPdField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrossEarningsForNICsYTD {
            get {
                return this.grossEarningsForNICsYTDField;
            }
            set {
                this.grossEarningsForNICsYTDField = value;
            }
        }
        
        /// <remarks/>
        public decimal AtLELYTD {
            get {
                return this.atLELYTDField;
            }
            set {
                this.atLELYTDField = value;
            }
        }
        
        /// <remarks/>
        public decimal LELtoPTYTD {
            get {
                return this.lELtoPTYTDField;
            }
            set {
                this.lELtoPTYTDField = value;
            }
        }
        
        /// <remarks/>
        public decimal PTtoUELYTD {
            get {
                return this.pTtoUELYTDField;
            }
            set {
                this.pTtoUELYTDField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalEmpNICInPd {
            get {
                return this.totalEmpNICInPdField;
            }
            set {
                this.totalEmpNICInPdField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalEmpNICYTD {
            get {
                return this.totalEmpNICYTDField;
            }
            set {
                this.totalEmpNICYTDField = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeeContribnsInPd {
            get {
                return this.empeeContribnsInPdField;
            }
            set {
                this.empeeContribnsInPdField = value;
            }
        }
        
        /// <remarks/>
        public decimal EmpeeContribnsYTD {
            get {
                return this.empeeContribnsYTDField;
            }
            set {
                this.empeeContribnsYTDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public enum FullPaymentSubmissionEmployeeEmploymentNIlettersAndValuesNIletter {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        X,
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        Z,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/22-23/1")]
    public partial class FullPaymentSubmissionFinalSubmission {
        
        private FullPaymentSubmission_YesType becauseSchemeCeasedField;
        
        private bool becauseSchemeCeasedFieldSpecified;
        
        private System.DateTime dateSchemeCeasedField;
        
        private bool dateSchemeCeasedFieldSpecified;
        
        private FullPaymentSubmission_YesType forYearField;
        
        private bool forYearFieldSpecified;
        
        /// <remarks/>
        public FullPaymentSubmission_YesType BecauseSchemeCeased {
            get {
                return this.becauseSchemeCeasedField;
            }
            set {
                this.becauseSchemeCeasedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BecauseSchemeCeasedSpecified {
            get {
                return this.becauseSchemeCeasedFieldSpecified;
            }
            set {
                this.becauseSchemeCeasedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateSchemeCeased {
            get {
                return this.dateSchemeCeasedField;
            }
            set {
                this.dateSchemeCeasedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSchemeCeasedSpecified {
            get {
                return this.dateSchemeCeasedFieldSpecified;
            }
            set {
                this.dateSchemeCeasedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FullPaymentSubmission_YesType ForYear {
            get {
                return this.forYearField;
            }
            set {
                this.forYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForYearSpecified {
            get {
                return this.forYearFieldSpecified;
            }
            set {
                this.forYearFieldSpecified = value;
            }
        }
    }
}
