//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0 and generalised by hand.
// 

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

namespace Paytools.Rti.Model._2023;

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--", IsNullable = false)]
public partial class IRenvelope<T> : IRtiDocumentForTaxYear where T : IRtiDataTarget, new()
{
    private IRheader iRheaderField;

    private T content = new();

    /// <remarks/>
    public IRheader IRheader
    {
        get
        {
            return this.iRheaderField;
        }
        set
        {
            this.iRheaderField = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute("FullPaymentSubmission", typeof(FullPaymentSubmission))]
    [System.Xml.Serialization.XmlElementAttribute("EmployerPaymentSummary", typeof(EmployerPaymentSummary))]
    [System.Xml.Serialization.XmlElementAttribute("NINOverificationRequest", typeof(NINOverificationRequest))]
    public T Content
    {
        get
        {
            return this.content;
        }
        set
        {
            this.content = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheader
{

    private IRheaderKey[] keysField;

    private System.DateTime periodEndField;

    private IRheaderPrincipal principalField;

    private IRheaderAgent agentField;

    private IRheaderDefaultCurrency defaultCurrencyField;

    private bool defaultCurrencyFieldSpecified;

    private IRheaderManifest manifestField;

    private IRheaderIRmark iRmarkField;

    private IRheaderSender senderField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Key", IsNullable = false)]
    public IRheaderKey[] Keys
    {
        get
        {
            return this.keysField;
        }
        set
        {
            this.keysField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
    public System.DateTime PeriodEnd
    {
        get
        {
            return this.periodEndField;
        }
        set
        {
            this.periodEndField = value;
        }
    }

    /// <remarks/>
    public IRheaderPrincipal Principal
    {
        get
        {
            return this.principalField;
        }
        set
        {
            this.principalField = value;
        }
    }

    /// <remarks/>
    public IRheaderAgent Agent
    {
        get
        {
            return this.agentField;
        }
        set
        {
            this.agentField = value;
        }
    }

    /// <remarks/>
    public IRheaderDefaultCurrency DefaultCurrency
    {
        get
        {
            return this.defaultCurrencyField;
        }
        set
        {
            this.defaultCurrencyField = value;
            this.defaultCurrencyFieldSpecified = true;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DefaultCurrencySpecified
    {
        get
        {
            return this.defaultCurrencyFieldSpecified;
        }
        set
        {
            this.defaultCurrencyFieldSpecified = value;
        }
    }

    /// <remarks/>
    public IRheaderManifest Manifest
    {
        get
        {
            return this.manifestField;
        }
        set
        {
            this.manifestField = value;
        }
    }

    /// <remarks/>
    public IRheaderIRmark IRmark
    {
        get
        {
            return this.iRmarkField;
        }
        set
        {
            this.iRmarkField = value;
        }
    }

    /// <remarks/>
    public IRheaderSender Sender
    {
        get
        {
            return this.senderField;
        }
        set
        {
            this.senderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderKey
{

    private string typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderIRmark
{

    private IRheaderIRmarkType typeField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public IRheaderIRmarkType Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public enum IRheaderIRmarkType
{

    /// <remarks/>
    SAonly,

    /// <remarks/>
    generic,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public enum IRheaderSender
{

    /// <remarks/>
    Individual,

    /// <remarks/>
    Company,

    /// <remarks/>
    Agent,

    /// <remarks/>
    Bureau,

    /// <remarks/>
    Partnership,

    /// <remarks/>
    Trust,

    /// <remarks/>
    Employer,

    /// <remarks/>
    Government,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Acting in Capacity")]
    ActinginCapacity,

    /// <remarks/>
    Other,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderPrincipal
{

    private EmployerPaymentSummary_ContactDetailsStructure contactField;

    /// <remarks/>
    public EmployerPaymentSummary_ContactDetailsStructure Contact
    {
        get
        {
            return this.contactField;
        }
        set
        {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderAgent
{

    private string agentIDField;

    private string companyField;

    private IRheaderAgentAddress addressField;

    private EmployerPaymentSummary_ContactDetailsStructure contactField;

    /// <remarks/>
    public string AgentID
    {
        get
        {
            return this.agentIDField;
        }
        set
        {
            this.agentIDField = value;
        }
    }

    /// <remarks/>
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }

    /// <remarks/>
    public IRheaderAgentAddress Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public EmployerPaymentSummary_ContactDetailsStructure Contact
    {
        get
        {
            return this.contactField;
        }
        set
        {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderAgentAddress
{

    private string[] lineField;

    private string postCodeField;

    private string countryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Line")]
    public string[] Line
    {
        get
        {
            return this.lineField;
        }
        set
        {
            this.lineField = value;
        }
    }

    /// <remarks/>
    public string PostCode
    {
        get
        {
            return this.postCodeField;
        }
        set
        {
            this.postCodeField = value;
        }
    }

    /// <remarks/>
    public string Country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public enum IRheaderDefaultCurrency
{

    /// <remarks/>
    GBP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderManifest
{

    private IRheaderManifestReference[] containsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable = false)]
    public IRheaderManifestReference[] Contains
    {
        get
        {
            return this.containsField;
        }
        set
        {
            this.containsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/--entity--/--tax-year--/--version--")]
public partial class IRheaderManifestReference
{

    private string namespaceField;

    private string schemaVersionField;

    private string topElementNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
    public string Namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }

    /// <remarks/>
    public string SchemaVersion
    {
        get
        {
            return this.schemaVersionField;
        }
        set
        {
            this.schemaVersionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "NCName")]
    public string TopElementName
    {
        get
        {
            return this.topElementNameField;
        }
        set
        {
            this.topElementNameField = value;
        }
    }
}