//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Paytools.Rti.Model._2023 {

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequest_TelephoneStructure {
        
        private string numberField;
        
        private string extensionField;
        
        private NINOverificationRequest_WorkHomeType typeField;
        
        private bool typeFieldSpecified;
        
        private NINOverificationRequest_YesNoType mobileField;
        
        private bool mobileFieldSpecified;
        
        private NINOverificationRequest_YesNoType preferredField;
        
        private bool preferredFieldSpecified;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NINOverificationRequest_WorkHomeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NINOverificationRequest_YesNoType Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MobileSpecified {
            get {
                return this.mobileFieldSpecified;
            }
            set {
                this.mobileFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NINOverificationRequest_YesNoType Preferred {
            get {
                return this.preferredField;
            }
            set {
                this.preferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredSpecified {
            get {
                return this.preferredFieldSpecified;
            }
            set {
                this.preferredFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public enum NINOverificationRequest_WorkHomeType {
        
        /// <remarks/>
        home,
        
        /// <remarks/>
        work,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public enum NINOverificationRequest_YesNoType {
        
        /// <remarks/>
        no,
        
        /// <remarks/>
        yes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequest_ContactDetailsStructure {
        
        private NINOverificationRequest_ContactDetailsStructureName nameField;
        
        private NINOverificationRequest_ContactDetailsStructureEmail[] emailField;
        
        private NINOverificationRequest_TelephoneStructure[] telephoneField;
        
        private NINOverificationRequest_TelephoneStructure[] faxField;
        
        /// <remarks/>
        public NINOverificationRequest_ContactDetailsStructureName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public NINOverificationRequest_ContactDetailsStructureEmail[] Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Telephone")]
        public NINOverificationRequest_TelephoneStructure[] Telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fax")]
        public NINOverificationRequest_TelephoneStructure[] Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequest_ContactDetailsStructureName {
        
        private string ttlField;
        
        private string[] foreField;
        
        private string surField;
        
        /// <remarks/>
        public string Ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fore")]
        public string[] Fore {
            get {
                return this.foreField;
            }
            set {
                this.foreField = value;
            }
        }
        
        /// <remarks/>
        public string Sur {
            get {
                return this.surField;
            }
            set {
                this.surField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequest_ContactDetailsStructureEmail {
        
        private NINOverificationRequest_WorkHomeType typeField;
        
        private bool typeFieldSpecified;
        
        private NINOverificationRequest_YesNoType preferredField;
        
        private bool preferredFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NINOverificationRequest_WorkHomeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NINOverificationRequest_YesNoType Preferred {
            get {
                return this.preferredField;
            }
            set {
                this.preferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreferredSpecified {
            get {
                return this.preferredFieldSpecified;
            }
            set {
                this.preferredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1", IsNullable=false)]
    public partial class NINOverificationRequest {
        
        private NINOverificationRequestEmpRefs empRefsField;
        
        private NINOverificationRequestEmployee[] employeeField;
        
        /// <remarks/>
        public NINOverificationRequestEmpRefs EmpRefs {
            get {
                return this.empRefsField;
            }
            set {
                this.empRefsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employee")]
        public NINOverificationRequestEmployee[] Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmpRefs {
        
        private string officeNoField;
        
        private string payeRefField;
        
        private string aORefField;
        
        /// <remarks/>
        public string OfficeNo {
            get {
                return this.officeNoField;
            }
            set {
                this.officeNoField = value;
            }
        }
        
        /// <remarks/>
        public string PayeRef {
            get {
                return this.payeRefField;
            }
            set {
                this.payeRefField = value;
            }
        }
        
        /// <remarks/>
        public string AORef {
            get {
                return this.aORefField;
            }
            set {
                this.aORefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmployee {
        
        private NINOverificationRequestEmployeeEmployeeDetails employeeDetailsField;
        
        private NINOverificationRequestEmployeeEmployment employmentField;
        
        /// <remarks/>
        public NINOverificationRequestEmployeeEmployeeDetails EmployeeDetails {
            get {
                return this.employeeDetailsField;
            }
            set {
                this.employeeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public NINOverificationRequestEmployeeEmployment Employment {
            get {
                return this.employmentField;
            }
            set {
                this.employmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmployeeEmployeeDetails {
        
        private string nINOField;
        
        private NINOverificationRequestEmployeeEmployeeDetailsName nameField;
        
        private NINOverificationRequestEmployeeEmployeeDetailsAddress addressField;
        
        private System.DateTime birthDateField;
        
        private NINOverificationRequestEmployeeEmployeeDetailsGender genderField;
        
        /// <remarks/>
        public string NINO {
            get {
                return this.nINOField;
            }
            set {
                this.nINOField = value;
            }
        }
        
        /// <remarks/>
        public NINOverificationRequestEmployeeEmployeeDetailsName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public NINOverificationRequestEmployeeEmployeeDetailsAddress Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public NINOverificationRequestEmployeeEmployeeDetailsGender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmployeeEmployeeDetailsName {
        
        private string ttlField;
        
        private string[] foreField;
        
        private string initialsField;
        
        private string surField;
        
        /// <remarks/>
        public string Ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fore")]
        public string[] Fore {
            get {
                return this.foreField;
            }
            set {
                this.foreField = value;
            }
        }
        
        /// <remarks/>
        public string Initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        public string Sur {
            get {
                return this.surField;
            }
            set {
                this.surField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmployeeEmployeeDetailsAddress {
        
        private string[] lineField;
        
        private string itemField;
        
        private NvrItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Line")]
        public string[] Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForeignCountry", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UKPostcode", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public NvrItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1", IncludeInSchema=false)]
    public enum NvrItemChoiceType {
        
        /// <remarks/>
        ForeignCountry,
        
        /// <remarks/>
        UKPostcode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public enum NINOverificationRequestEmployeeEmployeeDetailsGender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.govtalk.gov.uk/taxation/PAYE/RTI/NINOverificationRequest/1")]
    public partial class NINOverificationRequestEmployeeEmployment {
        
        private string payIdField;
        
        /// <remarks/>
        public string PayId {
            get {
                return this.payIdField;
            }
            set {
                this.payIdField = value;
            }
        }
    }
}
