# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Paytools.Core.sln'
      NuGetDirectory: ${{ github.workspace }}/nuget
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      
    - name: Test
      run: bash .github/runtests.sh
  
    - name: Pack
      run: dotnet pack --configuration Debug --output ${{ env.NuGetDirectory }}
      
    - name: Publish Nuget package for internal use
      if: ${{ github.repository_owner != 'paytools-fdn' }}
      run: |
        for file in "${{ env.NuGetDirectory }}/*.nupkg"
        do
          dotnet nuget push $file --api-key "${{ secrets.NUGET_REPO_TOKEN }}" --source "https://nuget.pkg.github.com/paytools-master/index.json" --skip-duplicate
        done